### ISSUE TITLE
Bulk Upload Feature not functioning on both staging and master branch 

### ISSUE THREAD

**Issue by choquette33** [peacecorps/medlink#466]
On staging branch the upload of a .csv leads to this error: 
![screenshot 2016-01-25 at 5 49 44 pm](https://cloud.githubusercontent.com/assets/2973990/12567241/1acb761c-c38c-11e5-9222-b0cd24324250.png)

On master branch (pcmedlink.org) an upload leads to nothing. After you choose a file to upload, you return to the users screen with just the choose file input highlighted. 
![screenshot 2016-01-25 at 5 50 55 pm](https://cloud.githubusercontent.com/assets/2973990/12567320/67d0cb92-c38c-11e5-9e4c-115a0f020598.png)

**Comment by jamesdabbs** [comment]
Per an earlier conversation with @aroberts01, the issue here is that the upload cannot accept a CSV with a `Country` column (as there are no provisions for uploading to multiple countries at once). We _do_ need an actual informative error message there, but things should work if you remove that column.

**Comment by jamesdabbs** [comment]
AFAIK, this is "working as intended" with that^. If we want to support multi-country uploads, that'll need to be a new feature; if not, we'll disallow the column and get country from the drop-down.
